import { IOrder } from "@/types/general";
import { mockCustomers } from "./mockCustomers";
import { mockProducts } from "./mockProducts";

const mockOrders: IOrder[] = [
  {
    id: "ORD-1024",
    customer: mockCustomers[0],
    dateOfOrder: "2023-05-15",
    products: mockProducts.slice(0, 2).map((pro) => ({ product: { ...pro }, quantity: 2 })),
    total: 400,
    fulfillmentStatus: "Pending",
    paymentStatus: "pending",
    shippingAddress: {
      name: "Sameen K A",
      houseName: "Kuruppassery",
      district: "Aalappuzha",
      state: "Kerala",
      country: "India",
      pincode: "688265",
      phoneNumber: "95626262626",
    },
  },
  {
    id: "ORD-1025",
    customer: mockCustomers[1],
    dateOfOrder: "2023-06-02",
    products: mockProducts.slice(1, 3).map((pro) => ({ product: { ...pro }, quantity: 1 })),
    total: 575,
    fulfillmentStatus: "Processing",
    paymentStatus: "complete",
    shippingAddress: {
      name: "John Doe",
      houseName: "Lakeview",
      district: "Kochi",
      state: "Kerala",
      country: "India",
      pincode: "682020",
      phoneNumber: "9876543210",
    },
  },
  {
    id: "ORD-1026",
    customer: mockCustomers[2],
    dateOfOrder: "2023-06-15",
    products: mockProducts.slice(1, 4).map((pro) => ({ product: { ...pro }, quantity: 3 })),
    total: 1999,
    fulfillmentStatus: "Shipped",
    paymentStatus: "complete",
    shippingAddress: {
      name: "Aarav Menon",
      houseName: "Rose Villa",
      district: "Trivandrum",
      state: "Kerala",
      country: "India",
      pincode: "695014",
      phoneNumber: "9123456789",
    },
  },
  {
    id: "ORD-1027",
    customer: mockCustomers[0],
    dateOfOrder: "2023-07-01",
    products: mockProducts.slice(0, 1).map((pro) => ({ product: { ...pro }, quantity: 4 })),
    total: 299,
    fulfillmentStatus: "Delivered",
    paymentStatus: "complete",
    shippingAddress: {
      name: "Sameen K A",
      houseName: "Kuruppassery",
      district: "Aalappuzha",
      state: "Kerala",
      country: "India",
      pincode: "688265",
      phoneNumber: "95626262626",
    },
  },
  {
    id: "ORD-1028",
    customer: mockCustomers[1],
    dateOfOrder: "2023-07-20",
    products: mockProducts.slice(3, 5).map((pro) => ({ product: { ...pro }, quantity: 1 })),
    total: 500,
    fulfillmentStatus: "Cancelled",
    paymentStatus: "pending",
    shippingAddress: {
      name: "John Doe",
      houseName: "Lakeview",
      district: "Kochi",
      state: "Kerala",
      country: "India",
      pincode: "682020",
      phoneNumber: "9876543210",
    },
  },
  {
    id: "ORD-1029",
    customer: mockCustomers[2],
    dateOfOrder: "2023-08-05",
    products: mockProducts.slice(4, 6).map((pro) => ({ product: { ...pro }, quantity: 2 })),
    total: 1749,
    fulfillmentStatus: "Processing",
    paymentStatus: "pending",
    shippingAddress: {
      name: "Aarav Menon",
      houseName: "Rose Villa",
      district: "Trivandrum",
      state: "Kerala",
      country: "India",
      pincode: "695014",
      phoneNumber: "9123456789",
    },
  },
];

export default mockOrders;