import { IProduct } from "@/types/general";

export const mockProducts: IProduct[] = [
  {
    id: "D1001",
    name: "Floral Summer Dress",
    description: "A lightweight floral summer dress perfect for casual outings.",
    category: "Women's Clothing",
    originalPrice: 49,
    offerPercentage: 10,
    stocks: 25,
    images: [],
    isPublished: true,
  },
  {
    id: "D1002",
    name: "Men's Casual Shirt",
    description: "Comfortable men's casual shirt made from breathable cotton.",
    category: "Men's Clothing",
    originalPrice: 39,
    offerPercentage: 15,
    stocks: 0,
    images: [],
    isPublished: true,
  },
  {
    id: "D1003",
    name: "Evening Gown",
    description: "Elegant evening gown designed for special occasions.",
    category: "Women's Clothing",
    originalPrice: 129,
    offerPercentage: 20,
    stocks: 0,
    images: [],
    isPublished: true,
  },
  {
    id: "D1004",
    name: "Kids' Cartoon T-Shirt",
    description: "Fun and colorful cartoon t-shirt for kids.",
    category: "Kids' Clothing",
    originalPrice: 19,
    offerPercentage: 5,
    stocks: 50,
    images: [],
    isPublished: true,
  },
  {
    id: "D1005",
    name: "Men's Formal Suit",
    description: "Premium men's formal suit for business and events.",
    category: "Men's Clothing",
    originalPrice: 199,
    offerPercentage: 25,
    stocks: 15,
    images: [],
    isPublished: true,
  },
  {
    id: "D1006",
    name: "Women's Denim Jacket",
    description: "Trendy women's denim jacket for casual wear.",
    category: "Women's Clothing",
    originalPrice: 89,
    offerPercentage: 10,
    stocks: 30,
    images: [],
    isPublished: true,
  },
  {
    id: "D1007",
    name: "Silk Saree",
    description: "Traditional silk saree with rich detailing.",
    category: "Traditional Wear",
    originalPrice: 149,
    offerPercentage: 15,
    stocks: 0,
    images: [],
    isPublished: true,
  },
  {
    id: "D1008",
    name: "Men's Hooded Sweatshirt",
    description: "Cozy men's hooded sweatshirt for everyday comfort.",
    category: "Men's Clothing",
    originalPrice: 59,
    offerPercentage: 10,
    stocks: 40,
    images: [],
    isPublished: true,
  },
  {
    id: "D1009",
    name: "Girls' Party Dress",
    description: "Beautiful party dress for young girls.",
    category: "Kids' Clothing",
    originalPrice: 39,
    offerPercentage: 10,
    stocks: 20,
    images: [],
    isPublished: true,
  },
  {
    id: "D1010",
    name: "Men's Ethnic Kurta",
    description: "Traditional men's ethnic kurta for festive occasions.",
    category: "Traditional Wear",
    originalPrice: 49,
    offerPercentage: 5,
    stocks: 0,
    images: [],
    isPublished: true,
  },
  {
    id: "D1011",
    name: "Women's Woolen Coat",
    description: "Warm woolen coat designed for winter wear.",
    category: "Winter Wear",
    originalPrice: 119,
    offerPercentage: 20,
    stocks: 10,
    images: [],
    isPublished: true,
  },
  {
    id: "D1012",
    name: "Kids' Winter Jacket",
    description: "Durable winter jacket to keep kids warm.",
    category: "Winter Wear",
    originalPrice: 69,
    offerPercentage: 10,
    stocks: 0,
    images: [],
    isPublished: true,
  },
  {
    id: "D1013",
    name: "Women's Kurti Set",
    description: "Stylish kurti set perfect for traditional wear.",
    category: "Traditional Wear",
    originalPrice: 59,
    offerPercentage: 15,
    stocks: 0,
    images: [],
    isPublished: true,
  },
];